### ISSUE TITLE
Visualization Code for CSI

### ISSUE THREAD

**Issue by bobvo23** [geekfeiw/apl#2]
Hi Fei Wang, thanks for the great paper and sharing the code repo.

In the paper, your team demonstrates the CSI data visualization in various profiles (figure 6, figure 7, figure 8). May you please share with us the methodology or the code to visualize the CSI raw data. Thank you.

**Comment by bobvo23** [comment]
What I really interested in is the filter function for your CSI signals. How do you get the filtered signal from your original signal.

**Comment by geekfeiw** [comment]
@bobvo23 Sorry for the late response. I don't know why I was not notified by the issues.

1. Talking to the filter function, actually, we did not apply any filters, this is because we use USRP and Clocks, the original signal is very clean. You could check this at the dataset we shared.  

2. Visualizing CSI data. We have 52 sub-carriers, and recorded for a period, making a CSI sample 
an matrix (M) with size of *N_sample x 52*. To visualize the CSI amplitude, we use plot(abs(M); to visualize the CSI phase, we use plot(angle(M))).

**Comment by geekfeiw** [comment]
@bobvo23 I have some experience to apply [Butterworth filters](https://en.wikipedia.org/wiki/Butterworth_filter) on CSI signal, and would like to share with you for possible help. 

Matlab code
```
% original_csi
[b, a] = butter(5, 2/100);
filted_csi = filter(b,a,original_csi);
```
Above is a 5-th ordered, low-pass Butterworth filter with low-pass frequency *2/100xsample_rate*. *original_csi* is the amplitudes or phases of raw CSI.

**Comment by bobvo23** [comment]
Thanks geekfeiw, the reason that I asked because your lines  are very smooth.
Let me try to apply the Butterworth filter to my signal.
